server:
  port: 8190

spring:
  datasource:
    username: dev
    password: ?7h3{<+2{47!..H
    url: jdbc:mysql://192.168.39.10:3306/itheima?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.39.10
    port: 6379



# 可以sql查看日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml